# Railway Deployment Configuration
# This file tells Railway how to deploy the application

[build]
  builder = "DOCKERFILE"
  dockerfilePath = "backend/Dockerfile"

[deploy]
  startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
  healthcheckPath = "/health"
  healthcheckTimeout = 30
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3

[env]
  PORT = "8000"
  PYTHONPATH = "/app"
  PYTHONUNBUFFERED = "1"
