services:
  # Backend API Service
  - type: web
    name: gyanforge-backend
    runtime: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: PYTHONUNBUFFERED
        value: 1
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: gyanforge-data
      - key: CORS_ORIGINS
        value: https://gyanforge-frontend.onrender.com
    healthCheckPath: /health
    
  # Frontend Static Site
  - type: static
    name: gyanforge-frontend
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://gyanforge-backend.onrender.com
      - key: REACT_APP_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Redis Cache Service
  - type: redis
    name: gyanforge-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []  # Allow all IPs

databases:
  # PostgreSQL Database
  - name: gyanforge-db
    databaseName: gyanforge
    user: gyanforge_user
