services:
  # Backend API Service (Docker)
  - type: web
    name: gyanforge-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: gyanforge-data
      - key: CORS_ORIGINS
        value: https://gyanforge-frontend.onrender.com
      - key: DATABASE_URL
        value: sqlite:///./gyanforge.db
    healthCheckPath: /health
